### ISSUE TITLE
Issues After Initial Installation

### ISSUE THREAD

**Issue by klighty** [BitCurator/bitcurator-access-webtools#63]
Hello,

Have been attempting to get bitcurator-access-webtools working for our digital preservation program.

After installing the webtools and all the dependencies, I've successfully been able to run the virtual machine, and access the landing page at 127.0.0.1:8080 and see the service running. However, I've been encountering two major issues:
1) After accessing the service, there is no option to access admin tools and/or run the scanner for the first time. 
2) After halting the virtual machine and then running it again, any attempts to access the service result in a 504 error.

I'm wondering if anyone might be able to provide some illumination to what might be causing these issues.

Best,
K

**Comment by kamwoods** [comment]
Closing as this repository is now end-of-life.
